### ISSUE TITLE
License allows the right to sell

### ISSUE THREAD

**Issue by 13steinj** [OgarProject/Ogar#167]
This was an issue, as shown by the forum post, and it has quite a simple solution.

Unfortunately, it makes the project, considered closed source, even though all other rights are given freely.

http://binpress.com/license/generator will let you create a custom license, where you can specifically revoke the right of commercial use, or, give specific terms for it, such as

>The right of commercial can be requested from the developer at developer@ogar.com; the developer will give the right of commercial use when, under his/her discretion, the developer of the project that is requesting that right; is requesting that right for a substantial derivative of the original project.

Unfortunately, revoking commercial use, with no conditions or any, makes the project no longer considered open source.

**Comment by dazdylz** [comment]
No, just keep it open source.

**Comment by Darwinkel** [comment]
Open-source means free as in able to read and modify source code, and NOT free as in beer.

> Unfortunately, revoking commercial use, with no conditions or any, makes the project no longer > > considered open source.

This is not true. It is possible to revoke commercial use, while still being open-source. It just means people may not distribute the (modified) source code for money.

I agree that the Apache 2.0 license is *too* permissive, and perhaps the [GPL v3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) would be a better choice. Scamming is pretty much pointless with the GPLv3 since you must disclose the source and you cannot sublicense.

**Comment by z3ntu** [comment]
GPLv3 would really be a better choice. At least for Ogarv2!

**Comment by forairan** [comment]
We're considering a change of license for Ogar 2, but for the current version of Ogar, there probably won't be a change of license.

>Unfortunately, revoking commercial use, with no conditions or any, makes the project no longer >considered open source.

Not necessarily. However, there is no license (to my knowledge) that revokes commercial use and is still OSS-compliant. The license most heavily under consideration right now for Ogar 2 is the GPL v3, because as @Darwinkel stated:
>Scamming is pretty much pointless with the GPLv3 since you must disclose the source and you cannot sublicense.

**Comment by 13steinj** [comment]
@Darwinkel, @forairan; I've gone through attempting to find an open source license that restricts commercial use for my own projects. All commercial use is actually in the open source definition; and once that right is taken away it's no longer considered open source, nor can it be used in open source projects.

Also, while the GPL v3 license may make it pointless, there will always be enough idiots in this world and enough con artists taking advantage of them.

**Comment by Darwinkel** [comment]
> Also, while the GPL v3 license may make it pointless, there will always be enough idiots in this world and enough con artists taking advantage of them.

That's why the project should (and luckily currently does) raise awareness by placing a couple of big warning signs on the homepage and GitHub page.

In all seriousness, if the GPLv3 (due to the requirement of stating changes and crediting the original author(s), among other things) and some big warnings don't stop you from getting scammed, the only person to blame is yourself.

**Comment by DaFudgeWizzad** [comment]
IDEA! This may be way off but...
You have to make at least 5 obvious changes to the client before selling, and if not then it must be stated before purchase.

**Comment by 13steinj** [comment]
@DaFudgeWizzad ; if you mean going off of my solution, that wouldn't work. You'd need to do it in proper legal terms else "5 obvious changes" means nothing. A better (not perfect) substitute:


>The right of commercial use can be requested from the Licensor at ogar@example.com. The Licensor shall, give this right if and only if, at the Licensor's discretion, 5 substantial changes to the Software have been made in the Licensee's derivative work.

**Comment by DaFudgeWizzad** [comment]
@13steinj Ohhh, okay. That makes sense, thanks!

**Comment by subv3rsion** [comment]
If you guys would like to continue the conversation, I'd suggest bringing it over to the Ogar community forums, as we are no longer accepting "issues" beyond actual issues with the Ogar source here.

Just so you're aware, a license has been chosen for Ogar 2 and more information will be available soon.
