### ISSUE TITLE
It is not run under Linux

### ISSUE THREAD

**Issue by jAKErCZ** [OgarProject/Ogar#174]
Hello I wanted agario install a linux server we have, but after entering the following command: 

root@vs9142:/home/apps/agario/Ogar# -u H /bin/sh -c "cd; /bin/node src/index.js "
-bash: -u: command not found
  
and nothing will happen.

**Comment by Ephemerality** [comment]
I'm assuming you ran the install script first?
This command didn't work because you left out the sudo part. `sudo -u ogar -H /bin/sh -c "cd; /bin/node src/index.js"`

**Comment by Darwinkel** [comment]
See [this](http://ogarproject.com/threads/beta-ogar-v1-debian-ubuntu-package-arch-linux-package-and-buildbot.9/) page for more information.

Use one of the following commands to launch Ogar in the foreground.

``` ~$ sudo -u ogar -H /bin/sh -c "cd; /usr/bin/node src/index.js"```

``` ~$ sudo -H /bin/sh -c "cd /installation/directory; /usr/bin/node src/index.js"```

The first command is preferred, since it launches Ogar as an unprivileged user, which is more secure (and the ogar user will only get installed with the Linux script). However, some distributions may require root privileges to launch Ogar, and the first command will thus not work.

Also note that some distributions may use ``` /usr/bin/nodejs ``` instead of ``` /usr/bin/node ```

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.
