### ISSUE TITLE
Cant start server

### ISSUE THREAD

**Issue by agariofann** [OgarProject/Ogar#199]
hi everyone i need help on starting my pryvate server am i the only one or are there other people with this problem   PLEASE HELP ME!!!!!!!!!!!

**Comment by maixuanhan** [comment]
Hi,
Why don't you read carefully README file or join the community chat/forum at http://ogarproject.com/ instead of creating an **issue** here. I think you would be supported well there. 

One tip that could help you quickly get supported, that please address you issue, what problem did you face, be specific, what were you steps, what was the output.. blah blah, that helps people understand the issue and could help you out.

Please don't post question like this one. If you are patient to read the old closed issues, you may find out that a lot of people posted question like you (and maybe you find your solution in there). That's super annoying. Honestly, when reading this question, I didn't want to help you add all but you are new on github so I have above few words.

**Comment by vram4** [comment]
It would be more helpful if you actually posted your question instead of screaming for help.

**Comment by agariofann** [comment]
i can start it, but i mean HOW can i join it?

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.
