### ISSUE TITLE
Agar.io server starting problem 

### ISSUE THREAD

**Issue by PineapplePuncher** [OgarProject/Ogar#272]
Last login: Fri Oct 30 19:54:38 on ttys000
Stevans-MacBook-Pro:~ stevanperrino$ /Users/stevanperrino/Desktop/Ogar-master/src/Start.command ; exit;
module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/stevanperrino/index.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
/Users/stevanperrino/Desktop/Ogar-master/src/Start.command: line 2: pause: command not found
logout

[Process completed]

**Comment by JaraLowell** [comment]
Make sure, there where you initiate the server from aka where you start it, has to have node ws installed; So as you start it at root prompt, that means it need be there. Or go in to the src directory first and start it there after you did a node install ws

**Comment by PineapplePuncher** [comment]
Here is what I installed [ https://github.com/websockets/ws ] after, nothing happened, the same error came up. ♡

**Comment by The-MAsterV** [comment]
did u try " sudo node ogar "

**Comment by NatsuTheGreat** [comment]
If you are getting this, it mean you don't have *ws* installed. 

To install this, simply go to your command prompt (through the start button, or whatever windows your computer is) After that type it *npm install ws* It should pause for a second, then give you a ton of text, if you have words like "ERR" or so highlighted in purple or yellow, it was successfully installed. Otherwise contact me. 

Hope I helped.
