### ISSUE TITLE
Auto-reset

### ISSUE THREAD

**Issue by Lukkez** [OgarProject/Ogar#370]
Make a auto-reset feature on agarserv.ini to close and open the server, Ogar-Serv have this feature

**Comment by MastaCoder** [comment]
You can try running crontabs if you are on Linux for the time now :D

**Comment by Lukkez** [comment]
No, i can't, i'm Windows 10 User

**Comment by MastaCoder** [comment]
You can try getting the code for the reset from OgarServ and posting it into this one. I don't know if this would work because i don't use node.js a lot. There is a command called setTimeout where you can set a timer for a function to run. I have no clue if it would work on Ogar and you can simply have it call the exit function? I don't know much. Hope someone else can assist!

**Comment by Lukkez** [comment]
I not know node.js much, i know some javascript

**Comment by LegitSoulja** [comment]
Luckily, I just made a restart command :). Let me know if you still need it

**Comment by Lukkez** [comment]
No, and this is old, now ik javascript.
