### ISSUE TITLE
Virus Moving Node detection

### ISSUE THREAD

**Issue by NatsuTheGreat** [OgarProject/Ogar#374]
If that is what is does, how to make it stop checking for moving nodes only and make it check for ejected mass? For example I shoot a lot mass around the virus and shoot the virus at it, but it ignores all the mass, how do I change that? So that it would actually keep shooting once it hits all the ejected mass.

Thanks.

**Comment by retslac** [comment]
That's a good one.  Had to try that.

Add this function to Virus.js

```javascript
Virus.prototype.onAutoMove = function(gameServer) {
    var r = 100; // Checking radius

    var len = gameServer.nodesEjected.length;
    for (var i = 0;i < len;i++) {
        var check = gameServer.nodesEjected[i];

        var topY = check.position.y - r;
        var bottomY = check.position.y + r;
        var leftX = check.position.x - r;
        var rightX = check.position.x + r;

        if (this.collisionCheck(bottomY,topY,rightX,leftX)) {
            check.angle = this.angle; //make sure new virus shoots in same direction as this virus
            this.feed(check,gameServer);
            i--;
            len--;
        }
    }
};
```

Note that the new virus shooting angle is normally the same as the angle of the ejected cell it ate (which can be any direction in this case).  I added a line of code so that the new virus shoots in the same direction the original virus was moving in.  If you don't want that, then just remove the angle line.

**Comment by Agarian** [comment]
This guy is pro coder^

**Comment by NatsuTheGreat** [comment]
@retslac You're the best coder man. Love you.

**Comment by NatsuTheGreat** [comment]
@vram4 Can you close this now?
