### ISSUE TITLE
Board command issue

### ISSUE THREAD

**Issue by Ciao121** [OgarProject/Ogar#499]
Sometimes when I use the BOARD command:
ie Board MY NAME IS JOHN
I get the player username displayed
ie
1 JUMBO
2 JUMBO
3 JUMBO
4 JUMBO
in red
each player sees his own username...
Any Idea? :)

**Comment by retslac** [comment]
It's because of the latest agar.io client update.

You need to change a value in UpdateLeaderboard.js.  Search for this line:
```
view.setUint32(offset, 1, true);
```
change value of 1 into 0 and it should work again

**Comment by Ciao121** [comment]
Thank you,
but I saw this happening randomly. Is it possible that agar.io serve differents client's version?

**Comment by retslac** [comment]
It may look like it's random but it's actually not.  It also has to do with the nodes that are visible on the client's screen.

If nodeId 1 is visible on your screen (can even be some random food cell) you're gonna see your own nickname.  Latest client update has it even hardcoded now to always show your own nickname (for nodeId 1 only).

When you change custom text leaderboard to use nodeId 0, it should always work since nodeId 0 is never used for any cell so it can never be visible on your screen.

**Comment by Ciao121** [comment]
Thanks again.
The first update, changing
`view.setUint32(offset, 1, true);`
solved the issue.
For the second change I'll wait the cmmit in Ogar cose.
I just saw another leaderbord issue. Opening a new "ticket".
Thank you again.
