### ISSUE TITLE
Invitation to work on OpenAgar

### ISSUE THREAD

**Issue by Andrews54757** [OgarProject/Ogar#672]
@vram4  , Through your Ogar program, I was able to master JS from being a complete noob. I owe my skills to you. Using those skills, I am creating a new software called OpenAgar. I am inviting you to work on it with us. It would be nice to have a unified agar.io server software. I am also notifying others of the "Big Three" (Ogar, MultiOgar,OgarUL) for help. If you decline, I will be sad, yet I will yield.  Please join us. Lets make Agar.io great again. (BTW: I don't deal with politics) 

Andrews54757
AJS Development

**Comment by Luka967** [comment]
You're trying to revive an inactive person again? Chances are slim.

**Comment by Andrews54757** [comment]
Do you want to join?

**Comment by Luka967** [comment]
No.

**Comment by Andrews54757** [comment]
Okay, I know you hate AJS anyway

**Comment by LegitSoulja** [comment]
What's wrong with AJS? @Luka967? Note the same people that was there no longer exist (Non experienced ones)

AJS is more I guess home to anyone welcomed (no kids younger than 16 plz).

**Comment by Luka967** [comment]
@Andrews54757 @LegitSoulja Who said that I hate AJS? I just don't want to keep optimizing a private server for a dying game. It's time waste.

**Comment by Andrews54757** [comment]
Oh well. But the game is going to go back up after Im done with it. (I hope)

**Comment by NatsuTheGreat** [comment]
There are a lot still playing though.
I just hate the noobs coming on making issues that are a breeze to solve.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat That'll never happen. Besides, there's no support, other than community support on the forums, which will be documentation about future things.

**Comment by Luka967** [comment]
@Andrews54757 Oh really, you hope? Do you even have money and the technology (monitors, control "centers") to support servers that can hold at least 121,000 players, the peak player count for European servers, let alone 270,000 players from all regions all the time, time zone differences included?

If you can even squeeze in two even three maps into one server, that's still roughly 1,000 servers for 250 people each. Next goes the server pricing. If you use Linode servers (they're used by Agar.io itself) [with 2GB/1CPU](https://www.linode.com/pricing) variant, you'll need at least $10,000 to keep them running. Accompany additional $200 for extra stuff you buy for the servers left and right.

Agar.io is a dying game. Many skilled FFA/Teams players are quitting because of the bad server integrity, poor handling and cashcowing since Miniclip's arrival. No .io game can achieve a 500,000 player base again. None.

Remember that agar-inspired servers have limited options for customization, as all gamemodes are still based off of the seek-kill-repeat diagram. No exceptions. Even Zombie gamemode is not an exception.

You *can* drag in players via advertising and campaigns to OpenAgar, but that would be marginally less effective than something that would a company do.

**Comment by Andrews54757** [comment]
@Luka967 its open sourced. Anyone can open a server. I never said I was going to host it myself. And OpenAgar is getting faster and faster. I just finished putting bots in a separate child process.

**Comment by Andrews54757** [comment]
When you see the efficiency chart, you can see that everything is efficient except for collisions.

**Comment by LegitSoulja** [comment]
@Luka967 if times comes if we start hosting servers money isn't the issue. I can cover that, plus I have good enough services, and I know ALOT of people that can hook me up with good deals. I have friends that host aswell. Been dealing with hosting for years. If you're a new to this then you would be clueless.

I used to host minecraft servers. The max I could host was 5,000 servers. Minecraft compared to running something like OpenOgar is nothing. I'll be able to host 5000x3 more servers in that case.

You would be a fool having to pay more than 10,000 a month. Anyways, don't worry about us if you're not part of AJS.

**Comment by LegitSoulja** [comment]
I could easily spend more money on more server equipment to double that. Why purchase hosting? I don't know. The only hosting I would buy is to cover other countries other than the U.S.

**Comment by LegitSoulja** [comment]
Thought I'd share just in-case people don't know the things AJS is capable of doing.

**Comment by Andrews54757** [comment]
@Luka967 And I have many many plans for this. Remember, OpenAgar won't be like Agar.io. The name is a lie. It will have many differences to Agar.io

**Comment by Luka967** [comment]
I'm quitting. If you ever make any progress on OpenAgar and reviving this game before Agar.io shuts down, congratulations, you've 
@LegitSoulja If AJS is *really* capable of doing that do it already instead of bragging what it can all do.

**Comment by LegitSoulja** [comment]
@Luka967 well, ogarunlimited wasn't optimized enough, therefor it hasn't been done already.

But since OpenOgar is more optimized and flexible I can run alot of servers. But that will be next year when OpenOgar is fully done. So, there's no rush.

And it's not "bragging", it's me telling you that "Linode" isn't worth it. I have my own services. I used to host minecraft servers. I don't host anymore, so my services aren't being used at the moment, but will put them to use. .

**Comment by G047** [comment]
@LegitSoulja I don't think hes on about the servers, sadly luka is right.

**Comment by Faris90** [comment]
> @Andrews54757 @LegitSoulja Who said that I hate AJS? I just don't want to keep optimizing a private server for a dying game. It's time waste.

No it isn't

**Comment by Andrews54757** [comment]
This is ded. By yall
