### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Abdellbar** [OgarProject/Ogar#694]
Hi folks
It seems each time i try to run Node Ogar i get the flowing error:
/mnt/hgfs/Abdel/ogar2/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/mnt/hgfs/Abdel/ogar2/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/hgfs/Abdel/ogar2/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)

**Comment by Luka967** [comment]
Use an older version of `ws`.

**Comment by Abdellbar** [comment]
Thanks, I did with WS 1.1.1 , it's running now, however am getting 'Upgrade Required' on the browser. any ideas way would that happen 
<img width="298" alt="screen shot 2017-02-10 at 10 46 38" src="https://cloud.githubusercontent.com/assets/1244328/22822242/e7a830a2-ef7e-11e6-8298-0fbd28b9196f.png">

**Comment by Luka967** [comment]
You need to go through an agar-like client, not directly to the server via a browser.
For example:
Agar.io (pretty slow client and buggy): agar.io/?ip=abdelbarvm:443
c0nsume.me (old version and stable): c0nsume.me/private4.php?ip=abdelbarvm:443 (first set [this config](https://github.com/OgarProject/Ogar/blob/master/src/gameserver.ini#L28) to 0)

Also I recommend you check out this fork of Ogar since this repo isn't maintained by anyone as of now:
https://github.com/Megabyte918/MultiOgar-Edited
This fork is almost up to date with the new agar changes that happened a few weeks ago and is still being active. And it's a lot faster than this one.

**Comment by Abdellbar** [comment]
Oh cool, sorry for the stupid question, Thank you very much

**Comment by Luka967** [comment]
No problem xD
